# syntax=docker/dockerfile:1
# Use dev variant for building
FROM dhi.io/node:24-debian13-sfw-dev

LABEL maintainer.name="Ariel Biton"
LABEL maintainer.email="ariel@zplinux.eu"

ENV NODE_ENV=production
WORKDIR /usr/src/app

